#!/usr/bin/env bash

# Fix Nginx configuration to run as nginx user and listen on port 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Ensure nginx.conf permissions are secure
chmod 644 /etc/nginx/nginx.conf

# Check if Apache2 is running and kill it if so
if pgrep apache2 > /dev/null; then
	pkill apache2
fi

# Restart Nginx service to apply changes
service nginx restart
